PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX cedar: <http://bit.ly/cedar#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-code: <http://purl.org/linked-data/sdmx/2009/code#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX tablink: <http://bit.ly/cedar-tablink#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT (REPLACE(?label, "Cell.*=", "", "i") AS ?label_clean)
FROM <urn:graph:cedar-mini:rules>
FROM <urn:graph:cedar-mini:raw-data>
WHERE {
	?cell a tablink:RowHeader . 
	?cell rdfs:label ?label .        
	?cell tablink:sheet ?sheet.
	?sheet rdfs:label ?sheet_name.
	[ rdfs:label ?dataset_name] dcterms:hasPart ?sheet.
	?cell tablink:parentCell [tablink:value "gemeenten"].
	FILTER NOT EXISTS {
		?annotation a oa:Annotation.
		?annotation oa:hasTarget ?cell.
        }	
} ORDER BY ?label_clean
