# Observations with non-integer population counts

PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX cedarterms: <http://lod.cedar-project.nl/vocab/cedar#>
 
SELECT ?obs FROM <urn:graph:cedar-mini:release> WHERE {
       ?obs a qb:Observation .
       ?obs cedarterms:population ?population .
       FILTER (datatype(?population) != xsd:integer)
}