# Temporarily absent females per municipality, 1879
 
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX cedar: <http://bit.ly/cedar#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-code: <http://purl.org/linked-data/sdmx/2009/code#>
 
SELECT ?municipality (SUM(?pop) AS ?tot)
FROM <urn:graph:cedar-mini:release>
WHERE { ?obs a qb:Observation . 
        ?obs cedar:population ?pop . 
        ?obs sdmx-dimension:sex sdmx-code:sex-F .
        ?obs sdmx-dimension:refArea ?municipality .
        ?obs cedar:residenceStatus <http://bit.ly/cedar-residenceStatus#TijdelijkAfwezig> .           
        ?slice a qb:Slice.
	?slice qb:observation ?obs.
	?slice sdmx-dimension:refPeriod 1879 .
        FILTER (NOT EXISTS {?obs cedar:isTotal ?total }) .
} GROUP BY ?municipality ORDER BY ?municipality
