# List of top 100 most occurring header in all the raw dataset

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX cedar: <http://lod.cedar-project.nl:8888/cedar/resource/>
PREFIX maritalstatus: <http://bit.ly/cedar-maritalstatus#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-code: <http://purl.org/linked-data/sdmx/2009/code#>
PREFIX cedarterms: <http://bit.ly/cedar#>
PREFIX tablink: <http://bit.ly/cedar-tablink#>
 
SELECT ?value (COUNT(?foo) as ?refs) FROM <urn:graph:cedar-mini:raw-data> WHERE {
	?foo a ?type .
	?foo tablink:value ?value .
	FILTER (?type in (tablink:ColumnHeader, tablink:RowHeader))
} GROUP BY ?value ORDER BY DESC(?refs) LIMIT 100
